logging:
  level:
    org.springframework: ERROR
    org.springframework.security: INFO
    com.netflix.config.sources.URLConfigurationSource: ERROR

spring:
  application:
    name: auth-service
  main:
    allow-bean-definition-overriding: true
  data:
    cassandra:
      keyspace-name: th_auth
      contact-points: ${CASSANDRA_HOST:localhost}
      schema-action: create_if_not_exists

server:
  port: 9292
  servlet:
      context-path: /auth





header:
  service:
    authorization: ${INTERNAL_AUTH_AUTHORIZATION}

eureka:
    client:
      serviceUrl:
        defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    instance:
      preferIpAddress: true


hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000000
feign:
  client:
    config:
      default:
        connectTimeout: 160000000
        readTimeout: 160000000



