version: '3'
services:

  cassandra:
    ports:
     - "9042:9042"
    image: cassandra:latest
    container_name: cassandra
    environment:
      DS_LICENSE: accept
      HOST: cassandradb
    volumes:
    - dbvolume:/var/lib/cassandra
    restart: always
    hostname: cassandradb
    networks:
     nano-network:
       aliases:
        - cassandradb

  person_db:
      image: postgres:9.6
      restart: always
      ports:
        - "5432:5432"
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=docker
        - POSTGRES_DB=person_local
      networks:
       nano-network:
         aliases:
          - person_db

  eureka-server:
        container_name: eureka-server       
        image: eureka-server:latest
        expose:
            - 8761
        ports:
            - 8761:8761
        networks:
            - nano-network
            
  gateway-server:
        container_name: gateway-server      
        image:  gateway-server:latest
        ports:
            - 8080:8080
        environment:
            - EUREKA_URI=http://eureka-server:8761/eureka
        networks:
            - nano-network
        links:          
            - eureka-server:eureka-server
        depends_on:          
            - eureka-server        
        logging:
            driver: json-file

  auth-service:
        container_name: auth-service
        image:  auth-service:latest
        ports:
            - 9292:9292
        environment:
            - REDIS_HOST=redis-server
            - REDIS_PORT=6379
            - CASSANDRA_HOST=cassandradb
            - EUREKA_URI=http://eureka-server:8761/eureka

        networks:
            - nano-network
        links:
            - eureka-server:eureka-server
        depends_on:
            - eureka-server
        logging:
            driver: json-file


  user-service:
        container_name: user-service
        image:  user-service:latest
        ports:
            - 9090:9090
        environment:
            - JAVA_OPTS=
                -DEUREKA_URI=http://eureka-server:8761/eureka
            - GATEWAY_SERVER=gateway-server
            - EUREKA_URI=http://eureka-server:8761/eureka
        networks:
            - nano-network
        links:          
            - eureka-server:eureka-server
        depends_on:          
            - eureka-server
        logging:
            driver: json-file

  person-service:
    image: person-service:latest
    container_name: person-service
    environment:
      - DATABASE_URL= person_db
      - GATEWAY_SERVER=gateway-server
      - EUREKA_URI=http://eureka-server:8761/eureka
      - DATABASE_USER=postgres
      - DATABASE_SEC=docker
    ports:
     - "9876:9876"
    depends_on:
     - person_db
    networks:
     nano-network:
       aliases:
        - person-service
  client-app:
          container_name: client-app
          image:  client-app:latest
          ports:
              - 8090:8090
          environment:
              - GATEWAY_SERVER=gateway-server
              - EUREKA_URI=http://eureka-server:8761/eureka
          networks:
              - nano-network
          links:
              - eureka-server:eureka-server
          depends_on:
              - eureka-server

          logging:
              driver: json-file

volumes:
  dbvolume:

networks:
    nano-network:
        driver: bridge
        
