spring:
  application:
    name: cloud-gateway

eureka:
    client:
      serviceUrl:
        defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    instance:
      preferIpAddress: true
      
hystrix:
  shareSecurityContext: false
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 30000
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 1
  OkToRetryOnAllOperations: true
  eureka:
    enabled: true

zuul:
  ignoredServices: '*'
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000

  routes:

    auth-service:
      path: /auth/**
      url: auth-service
      stripPrefix: false
      sensitiveHeaders:

    user-service:
      path: /user/**
      serviceId: user-service
      stripPrefix: false
      retryable: true
      sensitiveHeaders:

    person-service:
      path: /person/**
      serviceId: person-service
      stripPrefix: false
      retryable: true
      sensitiveHeaders:

    client-app:
          path: /client/**
          serviceId: client-app
          stripPrefix: false
          retryable: true
          sensitiveHeaders:




server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: routes, mappings
  endpoint:
     mappings:
       enabled: true
     routes:
       enabled: true



