spring:
  application:
    name: cloud-registery

eureka:
   client:
      registerWithEureka: false
      fetchRegistry: false


server:
   port: 8761

logging:
  level:
    com.netflix.config.sources.URLConfigurationSource: ERROR
